DROP TABLE IF EXISTS post;

CREATE TABLE message (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT,
  body TEXT,
  comment TEXT
);

